services:
  parakeet_ctc_asr:
    container_name: riva-asr
    image: nvcr.io/nim/nvidia/riva-asr:1.3.0
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]
    shm_size: 8GB
    environment:
      - NGC_API_KEY=${NGC_API_KEY}
      - NIM_HTTP_API_PORT=9000
      - NIM_GRPC_API_PORT=50051
      - NIM_TAGS_SELECTOR=name=parakeet-1-1b-ctc-riva-en-us,mode=str
    ports:
      - "9000:9000"
      - "50051:50051"

  fastpitch_hifigan_tts:
    container_name: fastpitch-hifigan-tts
    image: nvcr.io/nim/nvidia/riva-tts:1.3.0
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]
    shm_size: 8GB
    environment:
      - NGC_API_KEY=${NGC_API_KEY}
      - NIM_HTTP_API_PORT=9001
      - NIM_GRPC_API_PORT=50052
      - NIM_TAGS_SELECTOR=name=fastpitch-hifigan-en-us
    ports:
      - "9001:9001"
      - "50052:50052"

